name: flutter_final_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  equatable: ^2.0.3
  google_fonts: ^6.2.0
  cupertino_icons: ^1.0.2
  icons_plus: ^5.0.0
  http: ^1.2.0
  mongo_dart: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true